apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
    servicefor: pages
  name: pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
      servicefor: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
        servicefor: pages
    spec:
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: log-persistent-claim
      containers:
      - image: adityapratapbhuyan/pages:repo
        imagePullPolicy: Always
        name: pages
        ports:
          - containerPort: 8080
        env:
        - name: PAGE_CONTENT
          valueFrom:
              configMapKeyRef:
                name: pages-config-map
                key: PAGE_CONTENT
        volumeMounts:
        - name: log-volume
          mountPath: "/var/tmp/"
        readinessProbe:
          tcpSocket:
           port: 8080
          initialDelaySeconds: 150
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 150
        resources: {}
status: {}