apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
    servicefor: pages
  name: pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
      servicefor: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
        servicefor: pages
    spec:
      containers:
      - image: adityapratapbhuyan/pages:config
        name: pages
        ports:
          - containerPort: 8080
        env:
          - name: PAGE_CONTENT
            valueFrom:
              configMapKeyRef:
                name: pages-config-map
                key: PAGE_CONTENT
        resources: {}
status: {}